### ISSUE TITLE
When will instructions be updated?

### ISSUE THREAD

**Issue by TheoCoombes** [vigibot/vigicad#1]
Hi!

**First off, I love what you're doing and Vigibot is an amazing website.**
I apologise if you're already working on updating this.

Could you add screw information/finish the TODO parts?

Again, no rush though.
Thanks!

**Comment by lxtzfr** [comment]
Hello @TheoCoombes,

For the moment we can find the last updated documentation on robot maker forum:
https://www.robot-maker.com/forum/227-vigibot-english-documentation/

We have a lot more to do, we will do our best to update the readme.

Thanks :)

**Comment by TheoCoombes** [comment]
Okay, thanks a lot @alexandrewurtzfr 
Love the work!
